const ACCESS_TOKEN = 'accessToken';
const REFRESH_TOKEN = 'refreshToken';

const AUTH_ACTION_KEY = {
  SET_NOT_AUTH: 'SET_NOT_AUTH',
  SET_AUTHEN: 'SET_AUTHEN',
};

export { ACCESS_TOKEN, AUTH_ACTION_KEY, REFRESH_TOKEN };
